command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - 8000

env:
  - name: DATABRICKS_HOST
    value: https://fe-vm-vdm-serverless-5bvlle.cloud.databricks.com
  - name: LAKEBASE_INSTANCE_NAME
    value: vibe-coding-demo
  - name: LAKEBASE_DB_NAME
    value: vibe_coding_mike_boswell

